export const SITE_CONFIG = {
  name: "باشگاه ها | نینجا و سامورایی تهران Bugeiryu",
  description: "آکادمی تخصصی هنرهای رزمی نینجا و سامورایی",
  email: "info@ninjahouse.ir",
  phone: "09122078446",
  address: "تهران، خیابان ولیعصر، نبش خیابان شهید بهشتی، پلاک ۱۲۳۴",
  social: {
    instagram: "https://instagram.com/ninjahouse",
    telegram: "https://t.me/ninjahouse",
    youtube: "https://youtube.com/ninjahouse",
  },
};

export const COURSES = [
  {
    id: "ninjutsu",
    name: "نینجوتسو",
    description:
      "آموزش کامل فنون نینجا، استتار، حرکات آکروباتیک و تاکتیک‌های رزمی",
    level: "مقدماتی تا پیشرفته",
    duration: "۶ ماه",
    price: "۲,۵۰۰,۰۰۰",
    capacity: "۱۵ نفر",
    schedule: "شنبه و سه‌شنبه ۱۶-۱۸",
  },
  {
    id: "samurai",
    name: "سامورایی",
    description: "آموزش فنون کلاسیک سامورایی، کاتانا و فلسفه بوشیدو",
    level: "مقدماتی تا پیشرفته",
    duration: "۸ ماه",
    price: "۳,۲۰۰,۰۰۰",
    capacity: "۱۲ نفر",
    schedule: "یکشنبه و چهارشنبه ۱۶-۱۸",
  },
  {
    id: "self-defense",
    name: "دفاع شخصی",
    description: "تکنیک‌های مدرن دفاع شخصی ترکیب شده با فنون سنتی",
    level: "همه سطوح",
    duration: "۴ ماه",
    price: "۱,۸۰۰,۰۰۰",
    capacity: "۲۰ نفر",
    schedule: "دوشنبه و پنجشنبه ۱۸-۲۰",
  },
  {
    id: "ninja-ranger",
    name: "نینجا رنجر",
    description: "دوره ویژه کودکان و نوجوانان با رویکرد بازی و سرگرمی",
    level: "کودکان ۷-۱۴ سال",
    duration: "۶ ماه",
    price: "۲,۲۰۰,۰۰۰",
    capacity: "۱۲ نفر",
    schedule: "جمعه ۱۰-۱۲",
  },
  {
    id: "bugei-ryu",
    name: "بوگه یو ریو",
    description: "سبک سنتی و کامل هنرهای رزمی ژاپنی",
    level: "پیشرفته",
    duration: "۱۲ ماه",
    price: "۴,۰۰۰,۰۰۰",
    capacity: "۱۰ نفر",
    schedule: "شنبه و سه‌شنبه ۱۸-۲۰",
  },
  {
    id: "kogaryu",
    name: "کوگاریو نینجا",
    description: "سبک اختصاصی کوگاریو با تکنیک‌های منحصربفرد",
    level: "پیشرفته",
    duration: "۱۲ ماه",
    price: "۴,۵۰۰,۰۰۰",
    capacity: "۸ نفر",
    schedule: "یکشنبه و چهارشنبه ۱۸-۲۰",
  },
];

export const INSTRUCTORS = [
  {
    id: 1,
    name: "مهدی صلح دوست",
    title: "مربی درجه یک نینجا و سامورایی",
    rank: "دان ۸",
    experience: "۲۵ سال",
    specialties: ["نینجوتسو", "بوگه یو ریو", "دفاع شخصی"],
    bio: "بنیانگذار آکادمی نینجا تهران با بیش از ۲۵ سال تجربه در هنرهای رزمی ژاپنی",
    achievements: [
      "قهرمان مسابقات آسیایی ۲۰۱۵",
      "مربی سال ۱۳۹۸",
      'مؤلف کتاب "راه نینجا"',
    ],
  },
  {
    id: 2,
    name: "سرکار خانم صلح دوست",
    title: "مربی درجه یک نینجا",
    rank: "دان ۵",
    experience: "۱۸ سال",
    specialties: ["نینجوتسو", "کوگاریو", "نینجا رنجر"],
    bio: "اولین بانوی مربی نینجوتسو در ایران با سبک اختصاصی کوگاریو",
    achievements: ["مربی برتر بانوان ۱۴۰۰", "طراح دوره نینجا رنجر"],
  },
  {
    id: 3,
    name: "سعید همتکار",
    title: "مربی درجه یک سامورایی",
    rank: "دان ۶",
    experience: "۲۰ سال",
    specialties: ["سامورایی", "بوگه یو ریو", "کن‌جوتسو"],
    bio: "متخصص فنون کلاسیک سامورایی و فلسفه بوشیدو",
    achievements: ["دارنده کمربند مشکی کن‌جوتسو", "مدرس بین‌المللی"],
  },
];

export const ARTICLES = [
  {
    id: 1,
    title: "فلسفه بوشیدو: راه جنگجو",
    excerpt: "آشنایی با اصول هفت‌گانه سامورایی و تأثیر آن در زندگی مدرن",
    content: "...",
    author: "مهدی صلح دوست",
    date: "۱۵ دی ۱۴۰۳",
    category: "فلسفه رزمی",
    image: "/images/articles/bushido.jpg",
    readTime: "۸ دقیقه",
  },
  {
    id: 2,
    title: "تکنیک‌های پایه نینجوتسو",
    excerpt: "آموزش گام به گام حرکات ابتدایی و نحوه صحیح استتار",
    content: "...",
    author: "سرکار خانم صلح دوست",
    date: "۱۰ دی ۱۴۰۳",
    category: "آموزشی",
    image: "/images/articles/ninja-basics.jpg",
    readTime: "۱۲ دقیقه",
  },
  {
    id: 3,
    title: "تاریخچه کوگاریو",
    excerpt: "بررسی سبک منحصربفرد کوگاریو و ریشه‌های تاریخی آن",
    content: "...",
    author: "سعید همتکار",
    date: "۵ دی ۱۴۰۳",
    category: "تاریخی",
    image: "/images/articles/kogaryu.jpg",
    readTime: "۱۰ دقیقه",
  },
];
